import html2canvas from "html2canvas";
import jsPDF from "jspdf";
import { toast } from "sonner";

export interface PDFReportData {
  title: string;
  date: string;
  participants: string[];
  summary: string;
  topics: Array<{ title: string; content: string }>;
  followUps: Array<{ task: string; assignee: string; deadline: string }>;
}

export async function exportToPDF(reportData: PDFReportData): Promise<void> {
  toast.info("PDF 생성 중...");

  const container = document.createElement("div");
  container.style.cssText = `
    position: fixed;
    left: -9999px;
    top: 0;
    width: 800px;
    padding: 40px;
    background: white;
    font-family: 'Noto Sans KR', sans-serif;
    color: #1a1a1a;
  `;

  container.innerHTML = `
    <style>
      @import url('https://fonts.googleapis.com/css2?family=Noto+Sans+KR:wght@400;500;600;700&display=swap');
      * { font-family: 'Noto Sans KR', sans-serif; box-sizing: border-box; }
      .gold { color: #C9A227; }
      .gray { color: #666; }
      h1 { font-size: 28px; font-weight: 700; margin: 0 0 16px 0; color: #1a1a1a; }
      h2 { font-size: 18px; font-weight: 600; margin: 24px 0 12px 0; color: #1a1a1a; }
      h3 { font-size: 14px; font-weight: 600; margin: 0 0 8px 0; color: #1a1a1a; }
      p { font-size: 13px; line-height: 1.6; margin: 0 0 8px 0; color: #333; }
      .meta { font-size: 12px; color: #666; margin-bottom: 24px; }
      .section { margin-bottom: 24px; padding: 16px; background: #f8f8f8; border-radius: 8px; }
      .topic { margin-bottom: 16px; padding: 12px; background: #f0f0f0; border-radius: 6px; }
      .topic-num { color: #C9A227; font-weight: 600; margin-right: 8px; }
      .followup { padding: 12px; background: #fafafa; border-radius: 6px; margin-bottom: 8px; border-left: 3px solid #C9A227; }
      .followup-meta { font-size: 11px; color: #888; margin-top: 4px; }
      .header-bar { height: 4px; background: linear-gradient(90deg, #C9A227, #E5D188); margin-bottom: 24px; border-radius: 2px; }
      .footer { text-align: center; font-size: 10px; color: #aaa; margin-top: 32px; padding-top: 16px; border-top: 1px solid #eee; }
    </style>
    
    <div class="header-bar"></div>
    <p class="gold" style="font-size: 12px; font-weight: 600; letter-spacing: 1px; margin-bottom: 8px;">경영진 보고서</p>
    <h1>${reportData.title}</h1>
    <p class="meta">📅 ${reportData.date} &nbsp;&nbsp;|&nbsp;&nbsp; 👥 ${reportData.participants.join(", ")}</p>
    
    <div class="section">
      <h2 style="margin-top: 0;">📋 요약</h2>
      <p>${reportData.summary}</p>
    </div>
    
    <h2>📌 주요 논의 사항</h2>
    ${reportData.topics.map((topic, i) => `
      <div class="topic">
        <h3><span class="topic-num">0${i + 1}</span>${topic.title}</h3>
        <p style="margin: 0;">${topic.content}</p>
      </div>
    `).join('')}
    
    <h2>✅ 후속 조치 사항</h2>
    ${reportData.followUps.map((item, i) => `
      <div class="followup">
        <p style="margin: 0; font-weight: 500;">${i + 1}. ${item.task}</p>
        <p class="followup-meta">담당: ${item.assignee} &nbsp;|&nbsp; 기한: ${item.deadline}</p>
      </div>
    `).join('')}
    
    <div class="footer">Generated by MeetingMind | AI 기반 스마트 회의록 솔루션</div>
  `;

  document.body.appendChild(container);
  await document.fonts.ready;
  await new Promise(resolve => setTimeout(resolve, 500));

  try {
    const canvas = await html2canvas(container, {
      scale: 2,
      useCORS: true,
      logging: false,
      backgroundColor: '#ffffff',
    });

    const imgData = canvas.toDataURL('image/png');
    const pdf = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });

    const pdfWidth = pdf.internal.pageSize.getWidth();
    const pdfHeight = pdf.internal.pageSize.getHeight();
    const imgWidth = pdfWidth;
    const imgHeight = (canvas.height * pdfWidth) / canvas.width;
    
    let heightLeft = imgHeight;
    let position = 0;

    pdf.addImage(imgData, 'PNG', 0, position, imgWidth, imgHeight);
    heightLeft -= pdfHeight;

    while (heightLeft > 0) {
      position = heightLeft - imgHeight;
      pdf.addPage();
      pdf.addImage(imgData, 'PNG', 0, position, imgWidth, imgHeight);
      heightLeft -= pdfHeight;
    }

    const fileName = `회의록-${new Date().toISOString().split('T')[0]}.pdf`;
    pdf.save(fileName);
    toast.success("PDF 다운로드 완료!");
  } catch (error) {
    console.error('PDF generation error:', error);
    toast.error("PDF 생성 중 오류가 발생했습니다");
  } finally {
    document.body.removeChild(container);
  }
}
